runtime: java11

instance_class: F2

env: flex

entrypoint: java -Dserver.port=$PORT -jar build/libs/hamacasbackend-0.0.1-SNAPSHOT.jar

runtime_config:
  jdk: openjdk11

env_variables:
  DB_URL: jdbc:mysql://34.136.51.50:3306/hamacas?createDatabaseIfNotExist=true&serverTimezone=UTC
  DB_USER_NAME: root
  DB_PASSWORD: root
